var models = [
{_id:0,brand:'',models:[]},
{_id:1,brand:'alfaromeo',models:['156','brera','giulietta','gt','gtv','spider']},
{_id:2,brand:'amc',models:['matador']},
{_id:3,brand:'astonmartin',models:['db 9','dbs','rapide','v12 vantage ','v8 vantage','vantage','virage']},
{_id:4,brand:'attham',models:['sport']},
{_id:5,brand:'audi',models:['100','80','a1','a3','a4','a5','a6','a7','a8','q3','q5','q7','r8','rs3','rs4','rs5','s6','tt','tt rs','tts']},
{_id:6,brand:'austin',models:['classic car','healey','mini moke']},
{_id:7,brand:'bentley',models:['continental','continental-flying spur','continental-gt','continental-gt speed','continental-super sports','mulsanne']},
{_id:8,brand:'benz',models:['a-class','b-class','c-class','cla-class','clc-class','cl-class','clk-class','cls-class','e-class','g-class','gla-class','m-class','ml-class','other','r-class','s-class','sl-class','slk-class','slr-class','sls-class','sprinter','v-class']},
{_id:9,brand:'bmw',models:['classic-car','i3','i8','m3','m4','m5','m6','series 1','series 2','series 3','series 4','series 5','series 6','series 7','x1','x3','x4','x5','x6','z3','z4']},
{_id:10,brand:'buick',models:['electra']},
{_id:11,brand:'cadillac',models:['escalade','fleetwood','sedan deville','seville']},
{_id:12,brand:'chery',models:['a113','cross','qq','tiggo']},
{_id:13,brand:'chevrolet',models:['allroader','astro','aveo','c10','camaro','captiva','chevy van','colorado','corvette','cruze','express','lumina','optra','savana','sonic','spin','suburban','trailblazer','zafira']},
{_id:14,brand:'chrysler',models:['300c','300m','grand voyager','neon','new yorker','pt cruiser','voyager']},
{_id:15,brand:'citroen',models:['c3','c5','c8','ds3','ds4','evasion','jumper','xantia','xm','x-sara']},
{_id:16,brand:'daewoo',models:['chairman']},
{_id:17,brand:'daihatsu',models:['atrai ','atrai-7','copen','gran move','hijet','midget ii','mira','mira classic','opti','tanto']},
{_id:18,brand:'deva',models:['hercules']},
{_id:19,brand:'dfm',models:['mini truck','mini-van']},
{_id:20,brand:'dodge',models:['challenger','fargo','journey','royal']},
{_id:21,brand:'ferrari',models:['348','360 modena','360 spider','458 italia','458 spider','599 gtb','612 scaglietti','california','f355 spider','f430','f430 challenge','f430 spider']},
{_id:22,brand:'fiat',models:['132','1800','500','695 ferrari']},
{_id:23,brand:'ford',models:['aspire','continental','cortina','ecosport','escape','escort','everest','fiesta','focus','laser','ltd','mondeo','mustang','ranger','telstar']},
{_id:24,brand:'foton',models:['view']},
{_id:25,brand:'gmc',models:['sierra']},
{_id:26,brand:'honda',models:['accord','airwave','beat','brio','brio amaze','city','civic','crossroad','cr-v','cr-z','edix','elysion','freed','hr-v','insight','integra','jazz','legend','nsx','odyssey','prelude','s2000','spark','stepwgn','stream','today','vamos','vigor']},
{_id:27,brand:'hummer',models:['h2','h3']},
{_id:28,brand:'hyundai',models:['accent','elantra','grand starex','h-1','h-100','sonata','tucson','veloster']},
{_id:29,brand:'infinity',models:['fx30d']},
{_id:30,brand:'isuzu',models:['buddy','cameo','d-max(??02-06)','d-max(??05-11)','d-max(??12-15)','dragon eye(??96-99)','dragon power(??00-02)','elf','impulse','mu','mu-7','nkr','tfr ????????(??91-97)','trooper','v-cross','vertex']},
{_id:31,brand:'jaguar',models:['daimler','f-type','sovereign','s-type','xf-series','xjl-series','xjr','xj-series','xkr','x-type']},
{_id:32,brand:'jeep',models:['cherokee','cj6','dj-5','grand cherokee','willy','wrangler']},
{_id:33,brand:'kia',models:['carens','carnival','grand carnival','grand sportage','jumbo','picanto','pregio','soul','sportage']},
{_id:34,brand:'lamborghini',models:['aventador','diablo','gallardo','huracan','murcielago']},
{_id:35,brand:'lancia',models:['fulvia']},
{_id:36,brand:'landrover',models:['defender','discovery','freelander','range rover','series. 3']},
{_id:37,brand:'lexus',models:['ct200h','es300','es300h','gs250','gs300','is f','is250','is250c','is300h','ls400','ls430','ls460','ls460l','lx460','lx470 cygnus','nx300h','rx270','rx300','rx330','rx350','rx450h','sc430','soarer ']},
{_id:38,brand:'lotus',models:['elise','evora','exige','sport']},
{_id:39,brand:'maserati',models:['3200gt','4200gt','ghibli','granturismo','quattroporte','shamal']},
{_id:40,brand:'mazda',models:['2','3','323','323-astina','626','808','az-wagon','bt-50','bt-50 pro','cx-5','cx-7','cx-9','familia','fighter','lantis','luce','mpv','mx5','rx-7','rx-8','tribute']},
{_id:41,brand:'mclaren',models:['mp4-12c']},
{_id:42,brand:'mg',models:['classic.','mg6','mgf']},
{_id:43,brand:'mini',models:['austin classic','austin mini','cooper','one']},
{_id:44,brand:'mitsubishi',models:['3000 gto','attrage','champ','chariot','colt','evolution','fto','fuso','galant','g-wagon','jeep','l200-cyclone','l200-strada','l300','lancer','mirage','outlander','pajero','pajero mini','pajero sport','shogun','space runner','space wagon','triton','ultima']},
{_id:45,brand:'nissan',models:['180 sx','200 sx','300 zx','350z','370z','almera','big-m frontier navara','big-m frontier1-2','big-m(??89-98)','cedric','cefiro','cube','datsun','dayz','elgrand','fairlady z','figaro','gloria','gt-r','infiniti','juke','largo','leaf','livina','march','murano','nv','nx','s1210','pao','patrol','presea','primera','pulsar','rasheen','safari','s-cargo','s0446','sentra','serena','silvia','skyline','sunny','sylphy','teana','s0453']},
{_id:46,brand:'oldsmobile',models:['ninety eight','omega brougham']},
{_id:47,brand:'opel',models:['astra','calibra','corsa','kapitan','vectra']},
{_id:48,brand:'peugeot',models:['204','205','206','207','304','306','307','308','405','406','407','505','605','807','bipper','expert','rcz']},
{_id:49,brand:'pontiac',models:['firebird','grand prix']},
{_id:50,brand:'porsche',models:[' 911 carrera 4s','356','911 carrera','911 carrera s','911 carrera4','911 gt2','911 gt3','911 sport classic','911 targa 4','911 targa 4s','911 turbo','911 turbo s','928','968 carrera','993 targa','996 carrera','997 carrera','boxster','carrera','cayenne','cayman','macan','panamera','ruf']},
{_id:51,brand:'proton',models:['exora','gen2','neo','persona','preve','saga','savvy']},
{_id:52,brand:'rolls-royce',models:['corniche ii','ghost','phantom','silver shadow i','silver shadow ii','silver spirit ii ','silver spur ii ']},
{_id:53,brand:'rover',models:['623','75','820','mini.']},
{_id:54,brand:'saab',models:['9000cd','9000cde','9000cs','9000cse','900s','95','95 aero']},
{_id:55,brand:'seat',models:['alhambra','cordoba']},
{_id:56,brand:'skoda',models:['octavia']},
{_id:57,brand:'smart',models:['smart']},
{_id:58,brand:'ssangyong',models:['actyon','chairman','rexton','stavic']},
{_id:59,brand:'subaru',models:['b9 tribeca','brz','forester','glt','impreza','legacy','outback','r1','r2','wrx','xv']},
{_id:60,brand:'suzuki',models:['apv','caribian','carry','ertiga','esteem','every','grand vitara','hustler','jimny','lapin','swift','sx4','vitara','wagon r','wagon r plus']},
{_id:61,brand:'tata',models:['superace','xenon']},
{_id:62,brand:'toyota',models:['4runner','alphard','altezza,','aristo','avanza','avensis','bb','camry','cavalier','celica','celsior','corolla','corona','crown','duet','estima','fj cruiser','fortuner','ft-86','gaia','glanza','granvia','gt-86','harrier','hiace','hilux mighty-x','hilux sport rider','hilux tiger','s0550','hilux tiger d4d','hilux vigo','hilux vigo champ','hilux vigo d4d','innova','ipsum','kluger','land cruiser','s0555','ln','lucida','marino','mark ii','mark x','mega curiser','mr2','s0562']},
{_id:63,brand:'volkswagen',models:['amarok','beetle','caravelle','classic car','golf','karmann','multivan','new beetle','passat','polo','scirocco','sharan','touareg','transporter','up!','vento']},
{_id:64,brand:'volvo',models:['244','480','740','850','940','960','c30','c70','classic car.','s40','s60','s70','s80','s90','v40','v50','v60','v70','xc60','xc70','xc90']},

];

var brands = [];
for(var i=0; i<models.length; i++) {
    brands.push(models[i].brand);
}

localStorage.setItem('brands', JSON.stringify(brands) );
localStorage.setItem('models', JSON.stringify(models) );
